#!bin/bash
echo "Выберете гипервизор. Proxmox или WMware (пиши ТОЛЬКО 1 или 2)"
read -p "2) - proxmox 1) - WMware " Hypervisor
case $Hypervisor in
  1)
    int_type="ens33"
    ;;
  2)
    int_type="enp7s1"
    ;;
  *)
    echo "Неправльно. напиши 1 или 2"
    exit 1 
    ;;
esac
echo ""
echo -e "\e[32mИспользуется $int_type\e[0m"
echo ""
hostnamectl hostname hq-rtr.au-team.irpo

apt-get update $$ apt-get install iptables -y
echo ""
echo -e "\e[32mОбновлён репозиторий. установлен iptables\e[0m"
echo ""
sed -i 's/net.ipv4.ip_forward = 0/net.ipv4.ip_forward = 1/' /etc/net/sysctl.conf
sysctl -p
systemctl restart network

if ip link show $int_type up &>/dev/null; then
  iptables -t nat -A POSTROUTING -o $int_type -j MASQUERADE
  /etc/init.d/iptables save
  systemctl enable --now iptables
else
  echo ""
  echo -e "\e[31mИнтерфейс $int_type не найден. ты точно выбрал proxmox?"
  echo ""
fi
if [[ $Hypervisor == 2 ]]; then
  mkdir -p /etc/net/ifaces/{enp7s2,vlan{100,200,999}}
  touch /etc/net/ifaces/enp7s2/options
  echo "TYPE=eth" > /etc/net/ifaces/enp7s2/options
  echo $'100\n200\n999' | xargs -i bash -c 'echo -e "TYPE=vlan\nHOST=enp7s2\nVID={}" > /etc/net/ifaces/vlan{}/options'
else
  mkdir -p /etc/net/ifaces/{ens37,vlan{100,200,999}}
  touch /etc/net/ifaces/ens37/options
  echo "TYPE=eth" > /etc/net/ifaces/ens37/options
  echo $'100\n200\n999' | xargs -i bash -c 'echo -e "TYPE=vlan\nHOST=ens37\nVID={}" > /etc/net/ifaces/vlan{}/options'
fi
echo ""
read -p "Какой IP адресс и МАСКА для vlan100 ПО ЗАДАНИЮ? пиши без пробелов пример: 192.168.100.1/27" ip_vlan100
read -p "Какой IP адресс и МАСКА для vlan200 ПО ЗАДАНИЮ? пиши без пробелов пример: 192.168.200.1/28" ip_vlan200
read -p "Какой IP адресс и МАСКА для vlan999 ПО ЗАДАНИЮ? пиши без пробелов пример: 192.168.99.1/29" ip_vlan999
echo ""
echo "$ip-vlan100" > /etc/net/ifaces/vlan100/ipv4address
echo "$ip-vlan200" > /etc/net/ifaces/vlan200/ipv4address
echo "$ip-vlan100" > /etc/net/ifaces/vlan999/ipv4address

useradd net_admin
echo "net_admin:P@ssw0rd" | chpasswd
usermod -aG wheel net_admin
echo "WHEEL_USERS ALL=(ALL:ALL) NOPASSWD: ALL" > /etc/sudoers.d/net_admin

mkdir -p /etc/net/ifaces/gre1
touch /etc/net/ifaces/gre1/options
touch /etc/net/ifaces/gre1/ipv4address
echo "10.10.10.1/30" > /etc/net/ifaces/gre1/ipv4address
systemctl restart network

cat << EOF > /etc/net/ifaces/gre1/options
TYPE=iptun
TUNTYPE=gre
TUNLOCAL=172.16.1.2
TUNREMOTE=172.16.2.2
TUNOPTIONS='ttl 64'

EOF
apt-get update && apt-get install frr -y
cat <<'EOF' > /etc/frr/frr.conf
interface gre
 no ip ospf passive
exit
!
interface gre1
 ip ospf area 0
 ip ospf authentication
 ip ospf authentication-key P@ssw0rd
 no ip ospf passive
exit
!
interface vlan100
 ip ospf area 0
exit
!
interface vlan200
 ip ospf area 0
exit
!
interface vlan999
 ip ospf area 0
exit
!
router ospf
 passive-interface default
exit

EOF
systemctl enable -now frr
